### ISSUE TITLE
[Bug] Game stuck after future sight(?)

### ISSUE THREAD

**Issue by Togetik** [pagefaultgames/pokerogue#4878] opened 2024-11-15 18:37 UTC
### Describe the bug

Battled Meowstick in Metropolis - 91. Meowstick set up two future sights in a row before defeating Pawmot with another attack. Game got stuck at the defeat message. Interaction (pressing "C" ) possible, "M" or any dialogue-skip not possible.

### Reproduction

-Pawmot vs. wild meowstick in Metropolis - 91
-Meowstick sets up tweo future sights
-M defeats Pawmot with Psychic (or similar) before future sight can hit.
-game stuck, noch comment about future sight feiling etc.
![PR_Futuresight](https://github.com/user-attachments/assets/3d0451a4-00b6-4053-8be4-04624a4d9936)
![PR_futuresight_session_storage](https://github.com/user-attachments/assets/427a80b1-d29e-40a2-a58e-f8c5410182e3)
![PR_futuresight_cookie_storage](https://github.com/user-attachments/assets/5dad26c2-f211-4fcd-8811-5ddb4a2b6e4a)
![PR_futuresight_local_storage](https://github.com/user-attachments/assets/56cc02ae-ff41-4eca-a9fd-d9d9a5a30701)

### Expected behavior

-Expected future sight (1) to be messaged as fail as in original game
-be asked to change for another of my pokemon
-battle should continue
-be hit with future sight (2)

### Screenshots / Videos

(see reproduction)

### User data export file

Can't open ingame menu (only C, V and SHIFT show responses)

**Comment by PigeonBar** [comment] 2024-11-15 18:45
Duplicate of #1568. This will be fixed in the next update to main.

**Closed by PigeonBar** 2024-11-15 18:45 UTC
Labels: Triage
