### ISSUE TITLE
[BUG] First Pokemon on Team fainting at the very end of double battle to poison/recoil causes game to softlock and eventually freeze

### ISSUE THREAD

**Issue by ScalesSkull2906** [pagefaultgames/pokerogue#1867] opened 2024-06-06 13:04 UTC
**Describe the bug**
I was doing double battles with my Tyrunt (Strong Jaw and Reckless) and Monferno (Blaze and Moxie) and the move I used last on the two of them was Tyrunt's volt tackle and Monferno's Ice punch. Tyrunt used volt tackle and defeated the opponent fainting due to recoil at the end of the match and it got sent out again and Monferno was still on screen, the message "The downpour continues" is looping on the screen.

The events that happened in order at the end of the battle was
Tyrunt used volt tackle
fainting the enemy
got the exp
Tyrunt faints to recoil
Monferno's ice punch failed
Then a psyduck appeared
Then Tyrunt got sent out
"The downpour continues" now looping

![Screenshot (56)](https://github.com/pagefaultgames/pokerogue/assets/171942017/1078f57b-f5ff-42dc-8fee-9f80779a97d3)

**Device**
PC

**Comment by ScalesSkull2906** [comment] 2024-06-06 13:47
So it happened again, infernape died to poison at the end of a double battle and a similar thing is going on and it's allowing the enemy muk to gain a few buffs endlessly, which may allow me to win if it uses struggle at all because it is using the pp of the moves

**Comment by ScalesSkull2906** [comment] 2024-06-06 13:48
![image](https://github.com/pagefaultgames/pokerogue/assets/171942017/68264d2f-c791-454f-b646-b48dfa0d0cd8)

**Comment by ScalesSkull2906** [comment] 2024-06-06 13:48
So it freezes when it ran out of pp

**Comment by ScalesSkull2906** [comment] 2024-06-06 13:52
This may just be a general bug where if a pokemon dies at the end of a double battle and it is the first one on the team it'll cause this bug to happen

**Comment by flx-sta** [comment] 2024-07-24 06:07
Duplicate of #222

**Closed by flx-sta** 2024-07-24 06:07 UTC
Labels: Bug
