### ISSUE TITLE
[Bug] Enemy double battle partner's items display after faint in wild double battles

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#4771] opened 2024-11-01 08:05 UTC
### Describe the bug

In double battles against wild Pokemon, the enemy's items will display in the top right corner even after it's fainted, and it will persist until the battle ends.

### Reproduction

Get into a wild double battle with one of the enemy Pokemon holding an item, then defeat it.

### Expected behavior

The defeated Pokemon's items should disappear.

### Screenshots / Videos

![Pokerogue Item Display](https://github.com/user-attachments/assets/8d2448dc-0ded-4ca6-9bdf-cdc43eb97908)

### Additional context

This occurred in Endless Mode, so it may be an issue with that specifically.

**Comment by Snailman11** [comment] 2024-11-01 20:27
https://github.com/pagefaultgames/pokerogue/issues/3091

Duplicate of
[Bug] Enemy double battle partner's items display after faint in wild double battles

**Closed** 2024-11-01 20:29 UTC
Labels: Duplicate
