### ISSUE TITLE
Beat up deals no damage after the party's initial hit while using Multi Lens

### ISSUE THREAD

**Issue by LaukkaE** [pagefaultgames/pokerogue#1257] opened 2024-05-22 21:29 UTC
While using Multi-Lens, Beat up tries to index out of party bounds, causing hits to deal no damage.

https://github.com/pagefaultgames/pokerogue/assets/73663099/680ca6b6-3ea3-4141-9f33-1f810f5455a9

**Comment by Tempo-anon** [comment] 2024-07-27 23:13
Duplicate of #2767

**Closed by Tempo-anon** 2024-07-27 23:13 UTC
Labels: Bug, Move, Item
