### ISSUE TITLE
[BUG] U-Turn vs. Flame Body 

### ISSUE THREAD

**Issue by Knowaion** [pagefaultgames/pokerogue#1862] opened 2024-06-06 09:57 UTC
**Describe the bug**
Using U-Turn (Jumpluff) on a (switched in) Flame Body Pokémon (Talonflame) caused my own switched in Pokémon (Garganacl) to get burned.

**To Reproduce**
1. Have a Pokémon use U-Turn against a Pokémon with the ability Flame Body
2. Have Flamy Body trigger randomly
3. See the incoming Pokémon wrongly get burned

**Expected behavior**
The Pokémon switching in shouldn't get burned as it didn't make contact with the Flame Body Pokémon. The U-Turn user should get burned instead as it is switching out.

**Device**
Phone app

**Comment by Tempo-anon** [comment] 2024-06-06 16:30
Duplicate of https://github.com/pagefaultgames/pokerogue/issues/83

**Closed by Tempo-anon** 2024-06-06 16:30 UTC
Labels: Bug
