### ISSUE TITLE
Kirlia Evolution

### ISSUE THREAD

**Issue by RedRobot0** [pagefaultgames/pokerogue#1111] opened 2024-05-18 20:05 UTC
I don't think the reversion is necessary at all, the only reason it's how it works is because Gallade didn't exist yet and they needed a reason on why kirlia couldn't evolve, just leave it as is, just let these fictional creatures in this online website evolve either via choice or gender lock, the original way was completely irrational and likely wouldnt have happened if kirlia had gallade in gen 3

**Comment by Xavion3** [comment] 2024-05-18 20:08
Duplicate of #1101

**Closed by Xavion3** 2024-05-18 20:08 UTC
