### ISSUE TITLE
Transferring Max Mushroom keeps the original Pokemon G-Maxed

### ISSUE THREAD

**Issue by Dringodingo** [pagefaultgames/pokerogue#208] opened 2024-04-20 06:58 UTC
After a Pokemon has evolved with the Max Mushroom you can transfer it with out reverting back to normal. The new pokemon holding the item will not evolved until the game is reloaded. This seems like unintended behaviour. Seems like it would also work with mega stones but I have not been able to test this.
![G-max](https://github.com/pagefaultgames/pokerogue/assets/167604565/55a04aba-e49c-42b4-9c5b-a1db4dc759c1)
![image](https://github.com/pagefaultgames/pokerogue/assets/167604565/edaab686-6385-4679-8365-00abb6c4cf8e)

**Comment by Gammer0909** [comment] 2024-04-22 12:23
Wait, so the Pokémon given the Mushroom doesn't evolve until you reload, and then the old Pokémon keeps the G-Max, even after the reload?

**Comment by Dringodingo** [comment] 2024-04-23 11:32
Yes that's correct

**Comment by bennybroseph** [comment] 2024-05-16 11:06
still occurs


https://github.com/pagefaultgames/pokerogue/assets/13838608/dabd8659-6d8d-40d1-b733-1cc459ea2a6b

**Comment by Smewkie** [comment] 2024-05-29 20:10
Would like to add that this bug also apparently allows a duplicate of your form changing item to drop, for example having only one mega aggron on your team and transferring the Aggronite to another pokemon will allow Aggronite to spawn in the shop again.

**Comment by n2ash** [comment] 2024-06-01 05:14
It also causes some extremely weird knock-on behaviors (which may be limited to double-transformed fusions?): transferring Gyaradosite off of a fused Primal Groudon/Mega Gyarados not only doesn't affect the Mega, it causes it to semi-permanently lose the ability to deactivate the Mega at all. The menu ability will appear, but using it will only cause the menu option to go away, where it will stay until you *also* deactivate the Red Orb - but if you then activate the Gyaradosite, nothing changes, *and* you can't reactivate the Red Orb until you first deactivate the Gyaradosite again... which still changes nothing.

**Comment by flx-sta** [comment] 2024-07-23 05:58
Fixed since max mushroom is not considered transferable anymore 
Tested on `beta` (e84649854dfaff5dc02da255a09496332ba47e9c)

**Closed by flx-sta** 2024-07-23 05:58 UTC
Labels: Bug, Item, Game Design / Balance

**Comment by OreoCupcakes** [comment] 2024-07-23 06:11
> Fixed since max mushroom is not considered transferable anymore Tested on `beta` ([e846498](https://github.com/pagefaultgames/pokerogue/commit/e84649854dfaff5dc02da255a09496332ba47e9c))

Are Mega Stones still transferable?

Currently on live, it's possible to get mega stone rewards for Pokemon that have already mega evolved, i.e. Charizard/Mewtwo X getting the Y stone or a double Mega fused Pokemon getting the other stone. The only way to switch mega forms, if you encounter that scenario, was transferring stones in between waves. Where you would transfer the stone you want to another Pokemon, deactivate the form you don't want, transfer that unwanted stone to another mon, then transfer back the stone you want, all within the rewards screen.

**Comment by flx-sta** [comment] 2024-07-23 06:40
Might be worth investigating and if an issue to create a new one. I myself don’t gave the bandwidth right now
