### ISSUE TITLE
[BUG] - Double single battle

### ISSUE THREAD

**Issue by OriShalhon** [pagefaultgames/pokerogue#2814] opened 2024-07-05 16:09 UTC
After fainting own pokemon in double battle - it turns a single battle into double and the game freezes

**To Reproduce**

1. Enter double battle
3. have a faster pokemon attack the enemy and a slower pokemon attack a field-wide attack (everyone)
4. win the fight during the first attack, the 2nd attack from the slower pokemon kills the first pokemon
5. on next fight, the game prompts to add another pokemon to the field

The result is a single battle with two pokemons on the field and the game frozen

**Expected behavior**
When choosing the first pokemon after fainting it should be entered into a single battle

**Screenshots **
![image](https://github.com/pagefaultgames/pokerogue/assets/30048997/35a4cb7a-79fa-4c1e-b7c2-4dc33df9d010)

**Device**
running on Chromium browser (Brave)

**Additional context**
In Console of Errors - it infinitely returns error:
Texture *X* has no Frame *Y*

**Comment by DustinLin** [comment] 2024-07-06 17:51
can you post a video? i tried following your instructions and can't reproduce the problem:


https://github.com/pagefaultgames/pokerogue/assets/39450497/ed121f3f-0b01-495e-a8ca-b464e4667ff9

**Comment by OriShalhon** [comment] 2024-07-06 19:11
It was a pretty specific turn of event,
To be more specific,
It was a double battle right before a boss, and the first Pokémon fainted
after beating the enemy Pokémon in  the fight by an attack of the 2nd
Pokémon (I assume the order matters is the first one is supposed to stay
for the next fight)

**Comment by OriShalhon** [comment] 2024-07-09 08:58
@DustinLin looking at your video - its not the bug causing scenario
1. The first Pokémon (in your video Wailmer) attacks the enemy with an attack that faints the enemy team 
2. the second Pokémon ( in your video Charmander) attacks a battle-wide attack killing the first Pokémon (Wailmer)

what happens - 
1. the enemy Pokémon die from first attack 
2. with no enemy Pokémon left, the 2nd attack kills your own Pokémon 
3. bug should recreate after choosing Pokémon to replace fainted on

**Comment by flx-sta** [comment] 2024-07-25 06:35
Duplicate of #222

**Closed by flx-sta** 2024-07-25 06:35 UTC
Labels: Bug
