### ISSUE TITLE
[BUG] Future Sight does not behave like the mainline games

### ISSUE THREAD

**Issue by Smewkie** [pagefaultgames/pokerogue#1568] opened 2024-05-29 18:22 UTC
Currently, when a pokemon uses Future Sight, the move only stays in effect if that user stays in battle, in the mainline games, the move would normally stay in effect and do damage 2 turns later even if the user is switched out, however the move should be cancelled if the user faints, which is happening correctly.

**To Reproduce**
1: Use Future Sight
2: swap out for another pokemon
3: Future Sight does not activate the next turn.

**Additional context**
Future Sight in general seems like it's going to be a pain to get working correctly, it has a lot of fail cases that just aren't currently checked for, for example you shouldn't be able to use multiple Future Sights in a row on the same pokemon, I could not tell you if the damage from Future Sight is currently calculated with the users stats and abilities on the turn it hits or the turn it's used.
And to top it all off, you have Doom Desire which works the same way, I do not know if these bugs extend to Doom Desire however, if whoever looks into this checks out Doom Desire as well, do note that Future Sight and Doom Desire should normally block each other from working.

**Comment by GameOverFlowChart** [comment] 2024-06-12 12:06
Are you sure that it shouldn't hit if the use faints? I don't think that was the case in gen 3, I don't know the newer gens that well.

**Comment by Snailman11** [comment] 2024-08-04 16:09
Link to Discord's bug report: (Player's Future Sight goes away if player user switches)
https://discord.com/channels/1125469663833370665/1245140616392867950

**Comment by PigeonBar** [comment] 2024-10-21 04:03
Could not reproduce Future Sight activating Enigma Berry on the predict turn, so hopefully that bug is fixed now:

https://github.com/user-attachments/assets/808473e1-196c-40c0-99e5-7dc40c8c5d2b

**Closed** 2024-11-05 02:31 UTC
Labels: Move, P1 Bug
