### ISSUE TITLE
Killing a pokemon with contact effects using a move that swaps the user applies the effects to the swapped in pokemon

### ISSUE THREAD

**Issue by Varauk** [pagefaultgames/pokerogue#682] opened 2024-05-09 14:41 UTC
Killing (and maybe attacking in general, couldn't test that) an enemy with a move that swaps the user (e.g. flip turn) applies effects like paralysis from the enemy pokemons static to the swapped in pokemon, instead of the user of the move. At least from the pr description https://github.com/pagefaultgames/pokerogue/pull/165 this was supposed to be fixed. The only other somewhat related issue is https://github.com/pagefaultgames/pokerogue/issues/483.

Demo:

https://github.com/pagefaultgames/pokerogue/assets/35373497/f6480b26-1207-41ba-a5c0-a2db4cab1d0a

**Comment by Tempo-anon** [comment] 2024-07-24 21:23
Duplicate of #2860

**Closed by Tempo-anon** 2024-07-24 21:23 UTC
Labels: Bug, Move
