### ISSUE TITLE
Make Pokerouge Gender Bases Evos match Canon Evos instead.

### ISSUE THREAD

**Issue by AngelOShadows** [pagefaultgames/pokerogue#1103] opened 2024-05-18 18:24 UTC
There's no reason for the change quite frankly. Kirlia and Snorunt being gender based isnt totally accurate, just let them use the dawn stones to evolve into the desired forms - obviously the game can handle the stones.

**Comment by Xavion3** [comment] 2024-05-18 18:25
Duplicate of #1101

**Closed by Xavion3** 2024-05-18 18:25 UTC
Labels: duplicate

**Comment by AngelOShadows** [comment] 2024-05-18 18:28
Could I at least hear the reason why you feel it's necessary to keep them gender based? It's an odd change from canon, and it would be pretty disappointing if the only reason was because "they just are"

**Comment by Xavion3** [comment] 2024-05-18 18:34
I'd recommend reading the other issue I directed this to, a response has been posted there now.

**Comment by guest1511** [comment] 2024-05-18 18:37
> Could I at least hear the reason why you feel it's necessary to keep them gender based? It's an odd change from canon, and it would be pretty disappointing if the only reason was because "they just are"

I'm not a developer but I always took the change as one to make the forms more elegant and more clean in function. There are other annoying evolutions that were streamlined in Pokerogue due to the nature of the modes and it being a fangame, Runigerus being an extreme example. Gallade and Gardevoir are a mechanical dichotomy, special attacker versus physical attacker, psychic/fairy (or pure psychic in older games) versus psychic/fighting. It being gender based was the easiest way of doing this while giving control to the player, and compared to having the evolution be based on nature (if using something like Jolly/Adamant, go Gallade, if an attack dropping nature, go gardevoir), there's less rng for the player involved (you need to only worry about getting one of two genders that exist for the pokemon instead of worrying about 8 out of 20 natures, of which 4 are optimal whereas the gender, besides the evolution line, sweet kiss, and rivalry, don't have an affect on the pokemon, more niche situation than 10% on special defense when Gallade already has a solid special defense). This also means that before thinking about catching the krilia when its in the wild, you know exactly what it will evolve into instead of needing to catch it to make sure its evolution could fit into your team strategy. I'd also apply this similar reasoning to Snorunt's evolution, the dawn stone is an evolution stone with only two uses base game so instead of needing a new sprite and adding it into the great-tier item pool, just make them gender-locked so that its up to the player to make the mechanical choice because neither are too strong as to need the evolution item as a balancing act.


_(reposting this from the issue so that this isn't lost)_
As another player that likes the pokemon lines. I ask that if that the evolution must change, make it where Gardevoir and Gallade are as controllable as they are now and not locked behind stone evolution. It being gender locked is an elegant mechanical solution instead of nerfing Gallade behind a stone evolution. Something to note is that the discord server before lockdown did discuss a possible solution being that of having a prompt on evolution for krilia that you could choose whether to have it evolve into Gallade/Gardevoir regardless of gender when it hit level 30.
