### ISSUE TITLE
[Bug] Prankster Parting Shot used on Dark types shows "it doesn't affect [target]" but still shows stats lowering

### ISSUE THREAD

**Issue by fishsicles** [pagefaultgames/pokerogue#3112] opened 2024-07-23 18:11 UTC
### Describe the bug

As it says in the title. Saw this when my egg move Cottonee was switched into by a trainer with a Poochyena. The switch from Parting Shot doesn't happen, but the stat drops appear to.

### Expected behavior

All moves that activate Prankster should completely fail when used on Dark types.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

### Additional context

Occurred on locally hosted instance but latest version pulled from Git.

**Comment by DustinLin** [comment] 2024-07-24 01:53
able to reproduce on `beta`:

https://github.com/user-attachments/assets/8a1aaae2-f23d-47a3-a7b8-1117186b1757

expected behavior for confuse ray (sanity check):

Uploading prankster_confus.mov…

**Comment by DustinLin** [comment] 2024-07-24 01:54
i'll take a look into this...

**Comment by schmidtc1** [comment] 2024-07-24 13:45
https://github.com/pagefaultgames/pokerogue/blob/28c5dc6b59cd363c1dff55550bcaa620e7e29dda/src/data/move.ts#L7254-L7255
Likely due to `MoveEffectTrigger.PRE_APPLY`, it applies effects before `HitResult.NO_EFFECT` is checked.

**Comment by fishsicles** [comment] 2024-07-24 19:43
It also happens when Good As Gold would block Parting Shot.

**Comment by torranx** [comment] 2024-08-09 08:09
Fixed in https://github.com/pagefaultgames/pokerogue/pull/3195

**Closed by torranx** 2024-08-09 08:09 UTC
Labels: Bug
