### ISSUE TITLE
[Feature] Check IVs in Summary

### ISSUE THREAD

**Issue by Luoxcat** [pagefaultgames/pokerogue#2317] opened 2024-06-17 04:10 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the Feature**

**Additional context**

**Comment by zacharied** [comment] 2024-06-17 05:20
Duplicate of #770

**Comment by Dakurei** [comment] 2024-06-17 21:16
Closed in favor of #770

**Closed by Dakurei** 2024-06-17 21:16 UTC
Labels: enhancement
