### ISSUE TITLE
[Bug] Game freezes after finishing battle against Forretress with Iron Barbs

### ISSUE THREAD

**Issue by Araraura** [pagefaultgames/pokerogue#4832] opened 2024-11-09 09:14 UTC
### Describe the bug

I've had my game freeze after knocking out a Forretress with Iron Barbs before reaching the shop menu. I don't know what's causing this but I thought I should report this anyways and see if someone can figure out what's the issue here.

### Reproduction

Defeat Forretress (or maybe any pokemon?) with Iron Barbs

Just load the session file I provided here and knock it out. (I'm on commit de4ec5e so make sure you're using that as well)

### Expected behavior

The game should proceed to the shop and to the next waves normally.

### Screenshots / Videos

https://github.com/user-attachments/assets/c93551af-c079-47a8-a76e-7e2fe3786e19

### Session export file

[sessionData_Guest.txt](https://github.com/user-attachments/files/17686605/sessionData_Guest.txt)

### User data export file

[data_Guest.txt](https://github.com/user-attachments/files/17686606/data_Guest.txt)

**Comment by PigeonBar** [comment] 2024-11-09 13:44
https://github.com/user-attachments/assets/dbce6e42-6b35-4191-9067-21596130382f

I have been unable to reproduce this bug.

Does your F12 console show any error messages? They could be helpful to figure out why the crash occurs on your end.

**Comment by Araraura** [comment] 2024-11-09 16:47
> 20241109.Iron.Barbs.mp4
> 
> I have been unable to reproduce this bug.
> 
> Does your F12 console show any error messages? They could be helpful to figure out why the crash occurs on your end.

It does:
[console-export-2024-11-9_18-46-28.txt](https://github.com/user-attachments/files/17688681/console-export-2024-11-9_18-46-28.txt)

**Comment by PigeonBar** [comment] 2024-11-09 17:09
The console logs are pointing to the code for Rare Candies.

If you are playing on a local copy of the game, did you make any code changes that could be trying to give your Pokemon a Rare Candy at the end of a wave/biome?

**Comment by Araraura** [comment] 2024-11-09 17:50
> The console logs are pointing to the code for Rare Candies.
> 
> If you are playing on a local copy of the game, did you make any code changes that could be trying to give your Pokemon a Rare Candy at the end of a wave/biome?

Nope. I remember it usually gives me an EXP charm every 10 waves so maybe it has something to do with the fact that i've hit the cap for these?

**Comment by MokaStitcher** [comment] 2024-11-09 18:15
Is your local branch up to date?, there was a PR a while back that broke candies, but it's been fixed in #4561

**Comment by MokaStitcher** [comment] 2024-11-09 18:16
> Nope. I remember it usually gives me an EXP charm every 10 waves so maybe it has something to do with the fact that i've hit the cap for these?

The base game definitely doesn't do that

**Comment by Araraura** [comment] 2024-11-10 07:13
> Which browser and OS are you playing on?

Windows 11, firefox

**Comment by DayKev** [comment] 2024-11-10 07:34
Swapped to that commit and tested both Chrome and Waterfox (Firefox fork) and it didn't crash, though I'm on Windows 10... not that it should matter but you never know.
Strange.

**Comment by Araraura** [comment] 2024-11-17 08:31
> The console logs are pointing to the code for Rare Candies.
> 
> If you are playing on a local copy of the game, did you make any code changes that could be trying to give your Pokemon a Rare Candy at the end of a wave/biome?

ok figured it out it was because i commented out pokeballs from the rewards

**Closed** 2024-11-17 10:15 UTC
Labels: Triage, Beta
