### ISSUE TITLE
[BUG] PokeRouge presses the A button repeatedly sometimes

### ISSUE THREAD

**Issue by HyperRes** [pagefaultgames/pokerogue#2193] opened 2024-06-14 01:16 UTC
On some A presses the button gets held down until another button is pressed. I have confirmed this is not my keyboard and is the game. This happens randomly and inconsistently every 10 or so waves.

**Comment by c0nsy** [comment] 2024-06-27 23:23
Are you able to provide a video of this happening?
Has this occurred since this issue was opened?

I have tried to replicate but could not

**Comment by HyperRes** [comment] 2024-06-28 01:05
It's happened to me a few times on my laptop and once on mobile. I don't have any videos but it always happens when mashing through text while pokemon are attacking. I also can't confirm it 100% but its only happened to me when attack animations are off so maybe that's contributing.

**Comment by HyperRes** [comment] 2024-07-01 05:55
> Are you able to provide a video of this happening? Has this occurred since this issue was opened?
> 
> I have tried to replicate but could not

I caught a video of it happening just in time. I use standard controls and you can see I am pressing nothing. The inputs only stop after I press another key
https://github.com/pagefaultgames/pokerogue/assets/170381818/e4b8df73-eef6-4122-a904-c405b83c7bdb

**Comment by flx-sta** [comment] 2024-07-23 19:04
Duplicate of #1288

**Closed by flx-sta** 2024-07-23 19:04 UTC
Labels: Bug
