### ISSUE TITLE
item selection screen visual glitch [BUG]

### ISSUE THREAD

**Issue by Anjaconda** [pagefaultgames/pokerogue#2893] opened 2024-07-07 14:57 UTC
**Describe the bug**
occasionally when goes through endless mode past 1000 the game slows down and the item selection of the 6th items icon disappears with the item still there and can be selected  

**Screenshots / Videos**
<img width="1440" alt="Screenshot 2024-07-07 at 10 54 23 AM" src="https://github.com/pagefaultgames/pokerogue/assets/172850113/27d8b960-1837-49fb-aeff-6773e5b3c236">

**Device**
playing on Macbook on google Browser

(could be a skill issue)

**Comment by GorlockTheDestroyer64461** [comment] 2024-07-09 17:54
That happens to me all the time

**Comment by flx-sta** [comment] 2024-07-23 17:49
@Anjaconda  @GorlockTheDestroyer64461 Would you mind providing a session file where we can observe that?
To be able to upload it here in GitHub you have to change the file-extension from `prsv` to `txt` (don't worry. It's safe to do that)

**Comment by flx-sta** [comment] 2024-07-25 06:39
Duplicate of #1026

**Closed by flx-sta** 2024-07-25 06:39 UTC
Labels: Bug
