### ISSUE TITLE
Keyboard is not working properly on PC browser

### ISSUE THREAD

**Issue by hugolden** [pagefaultgames/pokerogue#3116] opened 2024-07-24 00:18 UTC
### Describe the bug

This may happen very easily on my account. Just on logging in the game, pressing any key may lead to the key pressed being kept pressing. Pressing another key may lead to the second button being kept pressing in sequence. For example, pressing down first may lead to the down button is kept pressed. Under this case, when I press up button, the down button and up button will be kept pressing in sequence in extremely high frequency.

Removing the focus of the page, like switching to another page, may stop the consistent button pressing. But once pressing any button, it happened again.

### Expected behavior

Any key pressing should only be responded once.

### Screenshots / Videos

https://github.com/user-attachments/assets/368b0996-73e7-44ac-b133-02ec29dfdde0

### What OS did you observe the bug on?

PC/Windows, Mac/OSX

### Which browser do you use?

Chrome

**Comment by Mewtwo2387** [comment] 2024-07-24 01:48
duplicate of #1288

**Comment by flx-sta** [comment] 2024-07-24 14:15
Duplicate of #1288

**Closed by flx-sta** 2024-07-24 14:15 UTC
Labels: Bug
