### ISSUE TITLE
[BUG] Sturdy does not reset itself if you heal back to full hp after tanking a hit

### ISSUE THREAD

**Issue by CDeltakai** [pagefaultgames/pokerogue#2234] opened 2024-06-15 00:02 UTC
**Describe the bug**

When a pokemon with sturdy tanks a hit, and then healed back to full HP in battle using healing moves, the next hit will still be able to OHKO them even though sturdy should normally reset itself after being healed to full hp.

**To Reproduce**

1. Use a pokemon with sturdy, in my case it was a gargancl, get hit and survive with sturdy.
2. Heal back to full HP using recover and other means (in my case the enemy was a lurantis which was slower than me and kept using Solar Blade, allowing me to protect and heal back to full)
3. Get hit with a move that would OHKO your pokemon while having healed back to full HP
4. Your pokemon still dies in one hit even though Sturdy should have let you survive.

**Expected behavior**

When healed back to full HP, sturdy should reset and allow you to tank another OHKO move.

**Screenshots / Videos**

- In this image my gargancl was knocked out despite healing back to full HP where sturdy should have protected me.
![image](https://github.com/pagefaultgames/pokerogue/assets/100399514/b7dc2919-d622-490f-b06b-1d7f96e78b3a)

**Device**

PC, Firefox

**Additional context**

**Comment by Mewtwo2387** [comment] 2024-06-15 00:29
Tested it using a custom recovery move that recovers 100%, sturdy managed to tank another hit. The code seems fine to me too.

Are you sure you're on 100% and not something like 99%?

**Comment by CDeltakai** [comment] 2024-06-15 00:35
Hmm it's possible that might have been the case and i wasn't looking at the exact numbers when it happened. That being said, if recover restores exactly half your HP, then two recovers should theoretically always restore my HP back to 100%. I'll have another check to see if I can get it happen again.

**Comment by minyukim** [comment] 2024-06-21 22:26
@Lucari10 This issue is under discussion here: https://github.com/pagefaultgames/pokerogue/pull/1877

**Comment by flx-sta** [comment] 2024-07-24 06:04
Duplicate of #1626

**Closed by flx-sta** 2024-07-24 06:04 UTC
Labels: Bug
