### ISSUE TITLE
[BUG] Leftovers not working properly

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1875] opened 2024-06-06 15:47 UTC
**Describe the bug**

Leftovers doesn't work if remaining HP is -1 of total HP. My Marshadow is lvl 139, HP is 441/442 and Leftovers didn't activate after the next 3 Pokemon I beat from a Gym Leader. It was working until HP reached 441/442.
**To Reproduce**

1. Have Leftovers on a Pokemon
2. Have 441/442 HP, or possibly any HP with -1 of total
3. See error

**Expected behavior**

Leftovers should work to get that +1 HP.
**Screenshots / Videos**

**Device**

PC
**Additional context**

**Comment by Ofenfrisch** [comment] 2024-06-07 14:21
https://github.com/pagefaultgames/pokerogue/blob/ffdbdc1139e8f5f3c795282b46a828d024bfe54d/src/modifier/modifier.ts#L863C1-L863C36

I think there is a "true" missing in the parameters here, then it should work.
As in:
`    if (pokemon.getHpRatio(true) < 1) {`

**Comment by flx-sta** [comment] 2024-07-24 06:04
Duplicate of #1626

**Closed by flx-sta** 2024-07-24 06:04 UTC
Labels: Bug
