### ISSUE TITLE
Sprites disappear when both sides lose a Pokemon in a gym battle

### ISSUE THREAD

**Issue by creative-pig** [pagefaultgames/pokerogue#1916] opened 2024-06-07 16:32 UTC
**Describe the bug**
When defeating a gym leader, if your own Pokemon faints on the same turn (for example, to burn damage), and you move on to the next area, sprites will disappear. All functionality remains, but both sides have no Pokemon sprites, until the game is reloaded.

**To Reproduce**
Defeat a Gym leader while your Pokemon is burned and low enough health to faint from its subsequent damage.

**Device**
Browser, PC

**Comment by creative-pig** [comment] 2024-06-09 10:55
I have found that this also applies to non-gym bosses at the end of biomes, and with weather chip damage.

**Comment by flx-sta** [comment] 2024-07-23 23:21
Duplicate of #222

**Closed by flx-sta** 2024-07-23 23:21 UTC
Labels: Bug, Duplicate
