### ISSUE TITLE
Switch moves vs. contact abilities.

### ISSUE THREAD

**Issue by TrainerX493** [pagefaultgames/pokerogue#1266] opened 2024-05-23 02:31 UTC
Use Flip Turn on a foe with Static > Pick a new Pokémon > New Pokémon switches in > Foe's Static activities > New Pokémon gets paralyzed.

Correct behavior would have Static paralyze the Flip Turn user before they switch out.

**Comment by Tempo-anon** [comment] 2024-06-06 16:43
duplicate of https://github.com/pagefaultgames/pokerogue/issues/83

**Closed by Tempo-anon** 2024-06-06 16:43 UTC
Labels: Bug, duplicate
