### ISSUE TITLE
One confirmed wrong interaction with type change move and abilities, and many more in question

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#1241] opened 2024-05-22 16:15 UTC
I went and confirmed in my personal copy of Scarlet that at least Electric type Revelation dance and volt absorb currently don't work as intended I.E it's not getting absorbed when it should.

Below is a minor list of examples I thought of to test out in Pokerogue and doubt they work correctly

Type change ability (Galvanize, liquid voice etc.) or type change moves (revelation dance) attacking into Flash fire, water absorb, sap sipper, Justified etc. => Not activating

Liquid voice Torch song attacking into Flash fire => Flash fire activating, Doubtful

Revelation dance with type change abilities (pixilate, refrigate etc.) => Revelation dance not getting affected by ability. 
This one actually makes me very unsure. Bulbapedia has conflicting information where the moves page says "it's not affected" while the ability pages list it as "is affected but no one with ability can learn them". Given lack of double battles in base game I can't test this myself.
https://bulbapedia.bulbagarden.net/wiki/Revelation_Dance_(move)
https://bulbapedia.bulbagarden.net/wiki/Pixilate_(Ability)

**Comment by LaukkaE** [comment] 2024-05-22 16:41
Duplicate of #527

**Closed by LaukkaE** 2024-05-22 16:41 UTC
