### ISSUE TITLE
Sturdy Preventing KO on pokemon minorly damaged same turn by priority move

### ISSUE THREAD

**Issue by lloyd-delacroix** [pagefaultgames/pokerogue#1187] opened 2024-05-21 01:54 UTC
Noticed a strange interaction where a pokemon with a small amount of damage is being hit and surviving with Sturdy. Here is a specific reproduction, but I've seen this same interaction occur in other in other doubles battles with these two moves. In this specific case both targets had sturdy, but I've also seen it happen with just a single pokemon with sturdy. I suspect it's something about the priority attack throwing off calculation order, but that's just speculation on my part.

Double Battle: Naganadel & Spidops vs Garganacl & Gigalith

Naganadel selects "dragon energy" (spread) as the move against both targets
Spidops selects "Feint" (priority) at the move against either target

Spidops Feint gets priority and goes first and damages the target. The health bar visibly moves a tiny amount
Naganadel uses dragon energy, but both enemies are reduced to 1hp rather than 1 surviving and one being killed

[sessionData_issue1187.zip](https://github.com/pagefaultgames/pokerogue/files/15383388/sessionData_issue1187.zip)

**Comment by Snailman11** [comment] 2024-08-23 23:41
I can't reproduce this using the session data provided, so closing it due to age

**Comment by Snailman11** [comment] 2024-08-23 23:42
I can't reproduce this, so closing it due to age

**Closed** 2024-08-23 23:42 UTC
Labels: Bug, Ability
