### ISSUE TITLE
Softlock when first pokemon in party faints after double battle ends

### ISSUE THREAD

**Issue by acarlson98** [pagefaultgames/pokerogue#730] opened 2024-05-11 01:58 UTC
I was in a double battle where I had a Persian and an Azumarill. The Persian was the first Poke in my party order. I was fighting a Naclstack and a Swoobat, but only the Naclstack was remaining, and it used Salt Cure on my Persian. I fainted the Naclstack, but then the residual Salt Cure damage fainted my Persian afterwards. When the next battle started, my Azumarill remained on the field and my trainer threw out my Persian, which should have been fainted, and softlocked the game. I was not able to open any menus and had to refresh the page, but after doing so I was past the double battle and had not lost any progress, so the severity of this issue is fairly low.

See image of softlocked game:
![image](https://github.com/pagefaultgames/pokerogue/assets/22945784/548b7729-508b-46b8-bacc-edb9617139ec)

See image of party after refreshing page:
![image](https://github.com/pagefaultgames/pokerogue/assets/22945784/344c5230-4656-4585-9a9a-c0ae75acd18a)

**Comment by flx-sta** [comment] 2024-07-25 06:16
Duplicate of #222

**Closed by flx-sta** 2024-07-25 06:16 UTC
Labels: Bug, Duplicate
