### ISSUE TITLE
Overhaul the Dialouge for the Rival

### ISSUE THREAD

**Issue by CodeTappert** [pagefaultgames/pokerogue#1376] opened 2024-05-25 17:34 UTC
I am currently localizing the rival dialogue and realized that is well, as some would say, a little "gender biased". And really makes use of some sterotypes.

I think the simplest way would be to have both rivals just use the same dialogue? And if not. Make the female rival less well, "clingy" (she is it way more then the male rival)

**Comment by Madmadness65** [comment] 2024-05-25 17:41
Is that not the appeal of Ivy as a character though? Making them both have shared gender-neutral dialogue would lessen the impact of what minimal story the game already has, while also generally making the characters more bland overall.

**Comment by CodeTappert** [comment] 2024-05-25 17:45
> Is that not the appeal of Ivy as a character though? Making them both have shared gender-neutral dialogue would lessen the impact of what minimal story the game already has, while also generally making the characters more bland overall.

For me personally it isnt as much of a problem. but it could be seen as a negative. 

It came up in Discord so i at least would like to dicuss this. So we  can, if we decide not to do it at least have this as a "we already talked about it" to link at

**Comment by CodeTappert** [comment] 2024-05-25 17:47
Maybe it is even viewed not as negative once we can freely choose the rivals gender. And it is not based on the players gender

**Comment by Adri1** [comment] 2024-05-25 18:08
I tend to agree with @CodeTappert 
For me, the Rival sould keep the exact same personality, no matter their gender. Basically like how it is in the games

**Comment by Adri1** [comment] 2024-05-25 18:15
However @CodeTappert, if the issue is accepted, I'd like you to keep their dialogues seperated and to not put them in common for both Ivy and Finn.
Because as I said in your PR, in French, Spanish, Italian and Portugese (at least) NPC dialogues, there is mantadory changes according make depending on player's gender. And the fact this seperation exists for the rival is very welcome

**Comment by Shadowth117** [comment] 2024-05-25 19:03
> I tend to agree with @CodeTappert For me, the Rival sould keep the exact same personality, no matter their gender. Basically like how it is in the official games when the Rival's gender depends on yours

To be clear, that's actually not how the rivals were done in the official games. Instead in the latest games you have the same rival regardless of player gender. But in earlier games, well:
https://youtu.be/HI1-PJ7Sy1w

Clearly there's a difference. And this extends to characters like May vs Brendan as well. I haven't dug deep into it, but having played every official mainline game through to gen 8 or so, it's something that I've noticed. 

At this point too, PokeRogue has already established a character for both of them and going by what you said here:

> For me personally it isnt as much of a problem. but it could be seen as a negative.

This is a requested change somewhat for the sake of it on your part.

Rather than changing these characters, perhaps it might be better to randomize which rival you get when you start classic mode? This would unfortunately burden translations into other languages as talked about above, but it would add some honest variety to runs since most players probably won't change their gender after picking it the first time.

Honestly, before I read this issue, I wasn't even aware there was a female rival in the game for that reason.

**Comment by Adri1** [comment] 2024-05-25 19:16
> This would unfortunately burden translations into other languages as talked about above
As long as in the end, evey and each NPC have a line per player gender, I think it's very nice idea

**Comment by Icehawk78** [comment] 2024-05-25 19:42
Just adding my two cents in, as the other participant in the original conversation around this - one possible fix (which might be worse/more effort) would be to simply add additional rivals in. If the gender-stereotyped rival language could come from rivals of either gender (ie have a super clingy Ivy and Ivan, and a macho Finn and Fiona, each pair of which could use the same dialogue, while not explicitly coming from a male and/or female character).

**Comment by TempsRay** [comment] 2024-05-28 00:42
> Is that not the appeal of Ivy as a character though? Making them both have shared gender-neutral dialogue would lessen the impact of what minimal story the game already has, while also generally making the characters more bland overall.

Yandere Ivy...

**Comment by Tempo-anon** [comment] 2024-06-06 16:42
Closing this issue for now since it seems like Finn and Ivy dialogue are staying for now as it's part of their iconic character design

**Closed by Tempo-anon** 2024-06-06 16:42 UTC
Labels: enhancement
