### ISSUE TITLE
Player and pokemon list can sometimes overlap with battle sprites

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#894] opened 2024-05-15 05:42 UTC
So I was playing casually and one of my mons (I don't remember which) died from poison at the end of a battle, but then I revived it with shop items. The game had me switch out anyway and then my player sprite persisted into battles. This only ended once I beat the boss.
![PokerogueMayBeBroken](https://github.com/pagefaultgames/pokerogue/assets/159862724/9aea5663-0b0e-42aa-83e0-4a8f4c3f8c47)

**Comment by PLMMJ-FH** [comment] 2024-05-15 06:22
Can confirm this only happens if the trainer sprite comes out.

**Comment by knispeja** [comment] 2024-05-22 08:31
Reproduced this locally by fainting with poison then reviving the mon. Technically the trainer sprite doesn't overlap in my example, but it's just because it wasn't followed by a trainer battle. I think this is the same bug:

https://github.com/pagefaultgames/pokerogue/assets/9343160/3261ab22-37c2-4b69-b171-8f029ce1b67f

**Comment by flx-sta** [comment] 2024-07-23 23:18
Duplicate of #222

**Closed by flx-sta** 2024-07-23 23:18 UTC
Labels: Bug, Duplicate
