### ISSUE TITLE
[BUG] Using Dive in Double-Battle Causes Replay of Dive Next Battle 

### ISSUE THREAD

**Issue by DaltJM** [pagefaultgames/pokerogue#2425] opened 2024-06-19 23:09 UTC
**Describe the bug**
Entering a double-battle with a Pokemon that knows dive, KOing opposing Pokemon prior to Dive Pokemon re-emerging then entering a single battle after causes dive to be used again with no user input.

**To Reproduce**
1. Have a Pokemon that knows Dive as your primary. 
2. Enter a double-battle with Pokemon that knows Dive. 
3. Use Dive move. 
4. Partner Pokemon KOs both opposing Pokemon prior to Dive Pokemon finishing the second half of Dive. 
5. End Double-Battle.
6. Enter Single-Battle.
7. Pokemon that was halfway through using Dive will now use Dive again without user interaction.

**Expected behaviour**
The expectation would be that the dive finishes and hits nothing if both opposing Pokemon have fainted like other non-multi-turn moves do.

**Device**
Both PC (Windows 10) and Phone (Android Galaxy S22).

**Comment by innerthunder** [comment] 2024-09-14 08:26
duplicate of #1991

**Closed by innerthunder** 2024-09-14 08:26 UTC
Labels: Duplicate
