### ISSUE TITLE
Soft lock after clicked ESC during "Do you want to switch pokemon" phase

### ISSUE THREAD

**Issue by antonevirus** [pagefaultgames/pokerogue#1797] opened 2024-06-04 15:39 UTC
I had just defeated a mon and wanted to access the egg menu
Clicked ESC repeatedly, and during the "Do you want to switch pokemon" phase i clicked ESC, which completely removed the selection menu.

I could not in any way get a selection to occur so i tried to restart and continue.

Now nothing loads in, all i see is the items i have, background and money.

![image](https://github.com/pagefaultgames/pokerogue/assets/5998716/826f17c3-8030-46fd-bcf9-90084686fa34)

**Comment by JakubHanko** [comment] 2024-06-04 15:41
Could possibly have something to do with:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at D2.getMoveset (index-144a02a1.js:14981:3953)
    at index-144a02a1.js:14979:15159
    at new Promise (<anonymous>)
    at D2.loadAssets (index-144a02a1.js:14979:15130)
    at initSessionFromData (index-144a02a1.js:14852:58436)
    at index-144a02a1.js:14852:59917
    at new Promise (<anonymous>)
    at M_.loadSession (index-144a02a1.js:14852:58083)
    at Hf.loadSaveSlot (index-144a02a1.js:14988:6983)
    at Object.handler (index-144a02a1.js:14988:5518)
```

**Comment by RNGezeus** [comment] 2024-06-04 18:02
Likely duplicate of #1736

**Closed** 2024-06-11 02:18 UTC
Labels: Bug
