### ISSUE TITLE
[BUG] Game freezes if the left-side pokemon dies to effects after winning a double battle, and the next battle is a singles

### ISSUE THREAD

**Issue by Mewtwo2387** [pagefaultgames/pokerogue#1970] opened 2024-06-08 21:24 UTC
**Describe the bug**

I was in a double battles with Rotom and Heracross. Rotom died to poison after the battle ended. As it is the Pokemon on the left side, it is the one used for the next battle. The next battle is a singles, so it sent out a dead Rotom and immediately asked for a replacement. I replaced it with Incineroar and the screen freezed here:

![image](https://github.com/pagefaultgames/pokerogue/assets/59531041/d4e06ea1-eec7-4f7e-b11d-9547eb6a55b7)

I forgot to screenshot the console and reloaded without preserving logs. But iirc, there are two errors reading properties of undefined when I checked. I'm not entirely sure if it is related to this bug.

Reloading the game placed me in the same singles battle but with Heracross there instead of both Heracross and Incineroar.

**To Reproduce**
1. Win a double battle when the left-side Pokemon is burned or poisoned, while having low HP.
2. If the next battle is a singles battle, the game will freeze after asking you to pick the replacement.

**Expected behavior**
Either,
1. It should just select the right-side pokemon as the one for the next battle, or
2. It should instead just ask you for a replacement, without sending out a dead Pokemon first.

And obviously the game shouldn't freeze.

**Device**
PC, Chrome version 125.0.6422.142 (64 bit)

**Comment by Mewtwo2387** [comment] 2024-06-08 21:33
Same issue from dichotoma on discord, also from the left-side pokemon dying to poison at the end of the battle:

![image](https://github.com/pagefaultgames/pokerogue/assets/59531041/333cba5f-1650-4278-8a73-90dd34d16049)

**Comment by flx-sta** [comment] 2024-07-23 23:22
Duplicate of #222

**Closed by flx-sta** 2024-07-23 23:22 UTC
Labels: Bug
