### ISSUE TITLE
[FEATURE] Move items before release

### ISSUE THREAD

**Issue by sudhamhebbarbrown** [pagefaultgames/pokerogue#2646] opened 2024-06-27 04:18 UTC
**Is your feature request related to a problem? Please describe.**
Users should have an option to move all items before releasing a pokemon. Or else you lose all items held by the released pokemon. 

**Describe the Feature**
1. When releasing a pokemon, the user is asked if he wants to move items. If yes, the already existing item mover is opened.
2. The system then continues to release the pokemon.
3. This interaction must not happen when a pokemon has no items.

**Comment by flx-sta** [comment] 2024-07-25 06:34
Duplicate of #790

**Closed by flx-sta** 2024-07-25 06:34 UTC
Labels: Enhancement
