### ISSUE TITLE
Expanding Force not work correctly in Psychic Terrain

### ISSUE THREAD

**Issue by qingyu-prestolabs** [pagefaultgames/pokerogue#1265] opened 2024-05-23 02:05 UTC
Just see the video below, Delphox triggers her passive Psychic Surge, and her move Expanding Force needs to select a target, which means it is not strengthened in Psychic Terrain.(just found this issue today, it's good before)

https://github.com/pagefaultgames/pokerogue/assets/115437705/07630687-1b47-4913-9e41-cf965bcfe920

another bug, sometimes when you reload the page while in a battle, Psychic Terrain disappears.(same way to find it easily by using Expanding Force in 2P battle). Not sure this bug is related to Delphox, cuz I don't use Tapu Lele often.

**Comment by jaimefd** [comment] 2024-05-23 18:07
But does it actually target both? I think if you click it, Expanding Force will be boosted and hit both. It's just a problem when selecting the target (of course that should be fixed too, just identifying the issue)

**Comment by qingyu-prestolabs** [comment] 2024-05-24 02:52
> But does it actually target both? I think if you click it, Expanding Force will be boosted and hit both. It's just a problem when selecting the target (of course that should be fixed too, just identifying the issue)

In my memory, I remembered it only attack the one targeted(not sure). I will test it later when server is back.

**Comment by qingyu-prestolabs** [comment] 2024-05-27 06:03
> But does it actually target both? I think if you click it, Expanding Force will be boosted and hit both. It's just a problem when selecting the target (of course that should be fixed too, just identifying the issue)

Hi, I think I get the root cause Expanding force not correct in psychic terrain. It is because Delphox fusion with Latios. After fusion, Expanding force work not correctly. And I have tested, it is actually only attacked one target rather than 2.

**Comment by Minwerdi** [comment] 2024-06-13 02:49
Hello!

Fusing with Latios actually gives Delphox Levitate in this case, which means that Delphox is no longer standing in the terrain and therefore does not get the additional effects of Expanding Force. More testing is probably helpful, but I suspect in this case it (Expanding Force) happens to be working as intended.

I'm also two weeks late, so disregard if this was already considered. ^_^

**Comment by qingyu-prestolabs** [comment] 2024-06-13 05:36
> Hello!
> 
> Fusing with Latios actually gives Delphox Levitate in this case, which means that Delphox is no longer standing in the terrain and therefore does not get the additional effects of Expanding Force. More testing is probably helpful, but I suspect in this case it (Expanding Force) happens to be working as intended.
> 
> I'm also two weeks late, so disregard if this was already considered. ^_^

wow. thx. you are right I forget it need to be stood in the terrain. thx.

**Comment by Snailman11** [comment] 2024-08-23 23:24
Link to Discord's Bug Report (expanding force not working in psychic terrain)
https://discord.com/channels/1125469663833370665/1273795261977854014

**Closed** 2024-08-29 21:26 UTC
Labels: Bug, Move, Ability
