### ISSUE TITLE
Switching moves that trigger abilities affect switched mon

### ISSUE THREAD

**Issue by TWHalikon** [pagefaultgames/pokerogue#83] opened 2024-04-11 02:27 UTC
Using a move like U-Turn on a Pokémon with the ability poison point will poison the Pokémon you switch into.

**Comment by mattrossdev** [comment] 2024-04-15 03:09
This still seems to be an issue.

ex: 
https://github.com/pagefaultgames/pokerogue/assets/13306707/0c5a8471-7a63-4f61-9af2-e31497fdee75


I think the problems are: 
1. In the ForceSwitchOutAttr class in data/move.ts, it's not applying the post-defend abilities to the attacker using the switch move. 
2. In the MoveEffectPhase in phases.ts it's incorrectly applying the post-defend ability to the switched in pokemon (~line 2392 currently). 

I didn't feel confident trying to fix this without breaking other abilities

**Comment by flx-sta** [comment] 2024-07-23 03:48
@TWHalikon @mattrossdev Is this issue still present?

**Comment by Tempo-anon** [comment] 2024-07-24 21:24
Duplicate of #2860

**Closed by Tempo-anon** 2024-07-24 21:24 UTC
Labels: Bug, Move
