### ISSUE TITLE
[BUG] Issue with Dive during a double battle against wild pokemon if you fail to catch the opponent

### ISSUE THREAD

**Issue by walt253** [pagefaultgames/pokerogue#1994] opened 2024-06-09 11:32 UTC
**Describe the bug**
When you use Dive during a double battle and try to catch the opponent the next turn, then the attack doesn't finish its sequence and the user remains hidden. Possibly this bug occurs for all those kinds of attacks that hides the users but I haven't checked it, just noticed with Dive.

**To Reproduce**
Have a pokemon with Dive and find a double battle.
Take down one opponent, let the other live.
Use the attack Dive, for simplicity switch the other ally with another pokemon.
Next turn throw a pokeball notice the pokemon is still in the "hiding" state if the pokeball failed to catch.

**Expected behavior**
The attack should finish its sequence after the pokeball failed to catch.

**Comment by Snailman11** [comment] 2024-08-24 03:55
Link to Discord's bug report: (during double battle, you can stall infinitely with dig/dive/fly while throwing pokeballs.)
https://discord.com/channels/1125469663833370665/1258189421048631306
-Video, ignore the unmovable eevee, that is part of Geomancy bug #1991 (Precharge moves reset when moving to another doubles battle)

**Comment by innerthunder** [comment] 2024-11-16 20:55
duplicate of #3750

**Closed by innerthunder** 2024-11-16 20:55 UTC
Labels: Move, P2 Bug
