### ISSUE TITLE
[BUG] Sprites do not show after all but the current pokemons fainted, and the current pokemon is replaced with a new captured pokemon

### ISSUE THREAD

**Issue by sonnyding1** [pagefaultgames/pokerogue#3079] opened 2024-07-20 23:59 UTC
**Describe the bug**
When all other pokemons in my party are fainted, and I only have my current pokemon alive, I capture the opposing wild pokemon and replace the current pokemon with the newly captured one. Then, starting from a new battle, both my pokemon's sprite and my opponent's sprite don't show.

**To Reproduce**
1. `POKEBALL_OVERRIDE` change to `active: true`, `[PokeballType.MASTER_BALL]: 6`
2. Choose a starter and start a new game, catch 5 pokemons so now you have a full team
3. Change `OPP_LEVEL_OVERRIDE` to `100`
4. Resume the game, get swept until you have 1 pokemon left
5. Use the last master ball to catch the opponent pokemon, and replace the only surviving pokemon with the captured pokemon
6. Go to next encounter, no sprite shows

**Expected behavior**
The sprites should appear normally. Also, "come back, xxx!" message probably needs some work too. Right now it probably just picks a random pokemon name and says come back.

**Screenshots / Videos**
![image](https://github.com/user-attachments/assets/f0bb1f63-4f39-4d2b-b437-04c1a2177d14)

**Device**
Windows, Chrome.

**Additional context**

**Comment by flx-sta** [comment] 2024-07-24 14:21
Related to #222 thus a duplicate of it

**Closed by flx-sta** 2024-07-24 14:21 UTC
Labels: Bug
