### ISSUE TITLE
[BUG] KO’d pokemon is sent out and game is softlocked

### ISSUE THREAD

**Issue by AEMARR** [pagefaultgames/pokerogue#1760] opened 2024-06-03 14:45 UTC
KO’d pokemon is sent out and partner pokemon remains after a double battle ends and single battle begins. Unable to menu through text boxes to be able to do anything.

**To Reproduce**
1. Enter a double battle against at least one wild pokemon with a damaging switch-out move (i.e. Volt Switch, Flip Turn, U-Turn, etc.)
2. Knockout one of the two wild pokemon, with the remaining one having the switching move
3. Enemy pokemon must knock out the pokemon in your first slot with the switchout move, ending the encounter
4. Choose an encounter reward
5. Next encounter must be a single battle
6. The KO’d pokemon is now automatically sent out, and the partner pokemon is not recalled

**Expected behavior**
The partner pokemon who is still alive should have automatically been set as the new primary pokemon, OR it should have been recalled, and the player prompted to choose which pokemon to send out

**Screenshots / Videos**
![IMG_0396](https://github.com/pagefaultgames/pokerogue/assets/51007546/8009225a-9172-47f1-9dc8-cf1f4a9c185e)

**Device**
Chrome, PC

**Additional context**
The pokemon that caused this glitch was a Dedenne using Volt Switch on my Luvdisc. Bug is fixed upon refreshing the page.

**Comment by torranx** [comment] 2024-06-04 07:22
i think this is already a known bug

**Comment by flx-sta** [comment] 2024-07-24 05:54
Duplicate of #222

**Closed by flx-sta** 2024-07-24 05:54 UTC
Labels: Bug
