### ISSUE TITLE
[BUG] Soft lock after dying from Naclstack's Salt Cure

### ISSUE THREAD

**Issue by BlastCom** [pagefaultgames/pokerogue#1531] opened 2024-05-29 02:55 UTC
<ins>**Describe the bug**</ins>
- Before the bug : 
    It's a 2v2 wild fight, Lycanroc and Nidoqueen on my side, Naclstack on the enemy side.
    Lycanroc was affected by the Salt Cure side effect.
    After giving the fatal blow on Naclstack, Lycanroc died from Salt Cure side effects.
    The combat ends, next foe follows.
- The bug :
    Swoobat appears, and Lycanroc magickly returns in combat over Nidoqueen's sprite.
    The game doesn't show the combat menu and Swoobat spam the attack Amnesia.
    The game loops and doesn't prompt any menu. Swoobat stats maxed out later on. *Didn't wait until PP's run out*
    At this stage, the game was soft-locked, Tried to refresh the browser.
- After a refresh : 
    The game loads at the start of Swoobat's fight.
    Lycanroc is dead as it should and Nidoqueen is sent in combat.
    The game continued as it should, but the bug didn't impact the game's progress.  
    
<ins>**To Reproduce**</ins>
- Steps can be done by recreating the scenario, as explained earlier, in dev mode or something.

<ins>**Expected behavior**</ins>
The game shouldn't: soft lock, lock me from attacking, foes loop attacking and sprites overlapping each other in a single fight.

<ins>**Screenshots / Videos**</ins>
![Screenshot_20240528-122614](https://github.com/pagefaultgames/pokerogue/assets/57077641/9362835f-0a4b-4013-8799-ccb244d161a0)
The screenshot was taken during Swoobat's loop spam attacking Amnesia. We can see Lycanroc and Nidoqueen sprites overlapping each other even though Lycanroc should be down by Naclstack's Salt Cure side effect from the previous fight.

<ins>**Device**</ins>
Played on Android, Google Pixel 2, LTE Connection, and Chrome browser - Installed the web app on the home menu with the Chrome install feature.

<ins>**Additional context**</ins>
I was walking outside while playing.
My guesses are a connection issue or Naclstack's Salt Cure implementation issue in a double fight.

**Comment by Smewkie** [comment] 2024-05-29 19:01
this appears to be the same bug that happens any time you finish a battle with a fainted pokemon, 2 pokemon get 'sent out' and overlap eachothers health bars and it gets fixed by a refresh.

more documentation isn't a problem though!

**Comment by flx-sta** [comment] 2024-07-24 05:47
Duplicate of #222

**Closed by flx-sta** 2024-07-24 05:47 UTC
Labels: Bug
