### ISSUE TITLE
[Bug] Missing interaction to reactivate a cancelled secondary fusion evolution

### ISSUE THREAD

**Issue by Flashfyre** [pagefaultgames/pokerogue#595] opened 2024-05-07 13:24 UTC

**Comment by flx-sta** [comment] 2024-09-03 04:26
> Hm.. let's say the player has a Mudkip and uh... idk Wurmple. They stopped Mudkip and Wurmple from evolving manually by pressing/holding B and turned off evolving for them. They then fuse Mudkip and Wurmple together but now they want to evolve Mudkip and Wurmple. When they go to the party menu they can turn back on evolutions for mudkip/the top part but they can't turn back evolutions on for Wurmple so then the bottom fusion is a wurmple forever

**Comment by flx-sta** [comment] 2024-09-04 15:08
This whole issue is not a `Bug` but a feature.
Right now fused mons are not designed to evolve both of the merged mons.

For now if somone decided to fuse a not fully evolved Pokemon it's by design and on them

**Closed** 2024-09-13 17:09 UTC
Labels: Miscellaneous, P2 Bug
