### ISSUE TITLE
[BUG] Arena flyout not reflecting spite/eerie spell correctly

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#2347] opened 2024-06-17 19:04 UTC
**Describe the bug**
It does not reflect the PP correctly

**To Reproduce**
Use Spite on an opponent

**Expected behavior**
The flyout reflects the accurate PP number

**Screenshots / Videos**
![](https://cdn.discordapp.com/attachments/1176874654015684739/1252336877055512658/image.png?ex=6671d91a&is=6670879a&hm=331133bf704d3f1ebb0298220d9d163d208dc6dff781f2339b149fab3ad2cd76&) after using spite

**Device**
n/a

**Additional context**
n/a

**Comment by schmidtc1** [comment] 2024-06-25 18:53
I think the problem is that the battle flyout container stores previous move info in an array and only updates it when a move is used, rather than referencing the opponent's current movesetPP.

**Comment by Snailman11** [comment] 2024-08-24 03:10
Closing as it was probably fixed by 3388 (mentioned)

**Closed by Snailman11** 2024-08-24 03:10 UTC
Labels: Bug
