### ISSUE TITLE
[BUG] Rival Pokemon getting an extra health checkpoint after reset

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1729] opened 2024-06-02 14:43 UTC
**Describe the bug**

When you face your rival that has a "boss" starter Pokemon she begins with, it starts with 1 HP checkpoint. But after resetting the game that Pokemon will start out with 2 HP checkpoints, making the fight a bit more difficult after trying again.
**To Reproduce**

1. Face your rival (I wrote this bug report while on level 145)
2. Notice her starter Pokemon only has 1 HP checkpoint right in the middle
3. Reset the game (F5) 
4. Notice how her starter Pokemon now has 2 HP checkpoints (at 1/3 and 2/3 HP)

**Expected behavior**

Expected to have the same HP checkpoint as before
**Screenshots / Videos**

**Device**

PC
**Additional context**

**Comment by Odizinne** [comment] 2024-06-02 16:16
Might be a duplicate of #1697

**Comment by Tempo-anon** [comment] 2024-06-06 16:37
Indeed, a duplicate of https://github.com/pagefaultgames/pokerogue/issues/1697

**Closed by Tempo-anon** 2024-06-06 16:37 UTC
Labels: Bug
